LIQUIBASE_DB_LIST = [
    "adminbackend",
    "circleprovider",
    "clients",
    "dataservice",
    "entity",
    "hummingbirdprovider",
    "idmindprovider",
    "kycmanager",
    "paymentmanager",
    "sanctionprovider",
    "sardineprovider",
    "trmlabsprovider",
    "trxmonmanager",
    "users",
    # "webforms",
    "worldpayprovider",
]
